### ISSUE TITLE
Suggestion: a more functional API

### ISSUE THREAD

**Issue by hliyan** [theekshanawj/js-string-validator#11]
This is awesome, except the API feels a bit more like Java.

How about:

```javascript
const strValidator = require('js-string-validator');
const isValid = strValidator.min(0).max(20).regex(/\s+/).includes('string').create();
console.log(isValid('a string')); // creates a function you can re-use
// > true
```

**Comment by theekshanawj** [comment]
Hi @hliyan, first of all, thank you for the suggestion. 
The way I thought about re-usability was wrapping expressions by a function, but this feels more elegant and expressive. 
I will create a version `2.0.0` by capturing your idea.

**Comment by theekshanawj** [comment]
@hliyan appreciate your reviews on https://github.com/theekshanawj/js-string-validator/pull/12

**Comment by theekshanawj** [comment]
https://github.com/theekshanawj/js-string-validator/pull/12 is merged to master therefore closing the issue.

**Comment by hliyan** [comment]
Sorry @theekshanawj , was very busy. Only saw this now. Looks good!

**Comment by theekshanawj** [comment]
@hliyan js-string-validator-2.0.0 is can be now found in https://www.npmjs.com/package/js-string-validator.
